title: "Jan Schwiddessen"
description: "Homepage of Jan Schwiddessen, PhD candidate in mathematical optimization at the University of Klagenfurt. Achievements, interests, publications, software, and talks."
email: "jan.schwiddessen [at] gmail.com"

author:
  name: "Jan Schwiddessen"
  avatar: "/assets/images/jan.jpg"
  bio: "Impact through algorithms --- approximation for large-scale systems."
  location: "Klagenfurt, Austria"
  email: "jan.schwiddessen [at] gmail.com"
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/jschwiddessen"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/jan-schwiddessen"
    - label: "Google Scholar"
      icon: "ai ai-google-scholar"
      url: "https://scholar.google.com/citations?user=7BgWcwkAAAAJ&hl=en"
    - label: "arXiv"
      icon: "ai ai-arxiv"
      url: "https://arxiv.org/a/schwiddessen_j_1"

url: "https://jan-schwiddessen.com"
baseurl: ""

remote_theme: "mmistakes/minimal-mistakes@4.27.3"
minimal_mistakes_skin: "default"
academicons: true

locale: "en"
timezone: "Europe/Vienna"

markdown: kramdown
kramdown:
  input: GFM
highlighter: rouge

permalink: /:title/

plugins:
  - jekyll-remote-theme
  - jekyll-include-cache
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag

collections:
  pages:
    output: true
    permalink: /:path/

defaults:
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

atom_feed:
  hide: true

exclude:
  - node_modules
  - vendor
  - .sass-cache
  - .jekyll-cache
  - README.md
  - Gemfile
  - Gemfile.lock

